version: '2'

services:
  python-flask-1:
    image: rapidfort/flaskapp
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-1
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - python3 app/app.py

  python-flask-2:
    image: rapidfort/flaskapp
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-2
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - python3 app/app.py
  
  python-flask-3:
    image: rapidfort/flaskapp
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-3
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - python3 app/app.py
    
  python-flask-4:
    image: rapidfort/flaskapp
    volumes:
      - ./configs/sample-server/app:/app
    container_name: python-flask-4
    cap_add:
      - SYS_PTRACE
    networks:
      - haproxy
    expose:
      - "8080"
    command:
      - python3 app/app.py

  haproxy:
    image: bitnami/haproxy
    user: root
    volumes:
      - ./coverage_script.sh:/opt/bitnami/scripts/coverage_script.sh
      - ./configs/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    container_name: haproxy
    networks:
      - haproxy
    cap_add:
      - SYS_PTRACE
    ports: 
      - '0.0.0.0::80'
    depends_on: 
      - python-flask-1
      - python-flask-2
      - python-flask-3
      - python-flask-4

networks:
  haproxy:
    driver: bridge
